spring:
  datasource:
    url: "jdbc:postgresql://localhost/laba-dstu"
    username: "postgres"
    password: "mustafa"
    sql-script-encoding: UTF-8

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: update

  thymeleaf:
    cache: false
